-- sql/01_schema.sql
BEGIN;

-- 1. Cleanup
DROP TABLE IF EXISTS AuditLog CASCADE;
DROP TABLE IF EXISTS Communication_Window CASCADE;
DROP TABLE IF EXISTS Alert CASCADE;
DROP TABLE IF EXISTS Telemetry CASCADE;
DROP TABLE IF EXISTS Maintenance_Log CASCADE;
DROP TABLE IF EXISTS Spacecraft_Subsystem CASCADE;
DROP TABLE IF EXISTS Spacecraft CASCADE;
DROP TABLE IF EXISTS Experiment CASCADE;
DROP TABLE IF EXISTS Mission_Phase CASCADE;
DROP TABLE IF EXISTS Ground_Station CASCADE;
DROP TABLE IF EXISTS Mission CASCADE;
DROP TABLE IF EXISTS Users CASCADE;

-- 2. Users Table (for Authentication & Auditing)
CREATE TABLE Users (
    user_id SERIAL PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    role VARCHAR(20) NOT NULL CHECK (role IN ('Admin', 'Commander', 'Engineer', 'Analyst')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 3. Core Tables
CREATE TABLE Mission (
    mission_id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    mission_code VARCHAR(50) UNIQUE, -- Generated by SP
    status VARCHAR(30) DEFAULT 'Planned' CHECK (status IN ('Planned', 'Active', 'Completed', 'Aborted', 'On Hold')),
    start_date DATE,
    end_date DATE,
    objectives TEXT,
    created_by INT REFERENCES Users(user_id),
    CHECK (end_date IS NULL OR start_date IS NULL OR end_date >= start_date)
);

CREATE TABLE Mission_Phase (
    phase_id SERIAL PRIMARY KEY,
    mission_id INT NOT NULL REFERENCES Mission(mission_id) ON DELETE CASCADE,
    phase_name VARCHAR(50) NOT NULL,
    start_time TIMESTAMP,
    end_time TIMESTAMP,
    status VARCHAR(30) DEFAULT 'Pending',
    CHECK (end_time IS NULL OR start_time IS NULL OR end_time >= start_time)
);

CREATE TABLE Spacecraft (
    spacecraft_id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    model VARCHAR(50),
    fuel_level NUMERIC CHECK (fuel_level IS NULL OR (fuel_level >= 0 AND fuel_level <= 100)),
    health_status VARCHAR(30) DEFAULT 'Operational',
    current_mission_id INT REFERENCES Mission(mission_id) ON DELETE SET NULL,
    manufactured_date DATE
);

CREATE TABLE Spacecraft_Subsystem (
    subsystem_id SERIAL PRIMARY KEY,
    spacecraft_id INT NOT NULL REFERENCES Spacecraft(spacecraft_id) ON DELETE CASCADE,
    name VARCHAR(50) NOT NULL, -- e.g., 'Propulsion', 'Life Support'
    health_score INT CHECK (health_score BETWEEN 0 AND 100),
    status VARCHAR(30) DEFAULT 'Operational',
    last_checked_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(spacecraft_id, name)
);

-- 4. Operational Tables
CREATE TABLE Maintenance_Log (
    log_id SERIAL PRIMARY KEY,
    subsystem_id INT NOT NULL REFERENCES Spacecraft_Subsystem(subsystem_id) ON DELETE CASCADE,
    description TEXT NOT NULL,
    technician_id INT REFERENCES Users(user_id),
    log_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    next_maintenance_due DATE
);

CREATE TABLE Telemetry (
    telemetry_id BIGSERIAL PRIMARY KEY,
    spacecraft_id INT NOT NULL REFERENCES Spacecraft(spacecraft_id) ON DELETE CASCADE,
    temperature NUMERIC,
    voltage NUMERIC,
    fuel_level NUMERIC,
    radiation NUMERIC,
    recorded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Alert (
    alert_id SERIAL PRIMARY KEY,
    spacecraft_id INT NOT NULL REFERENCES Spacecraft(spacecraft_id) ON DELETE CASCADE,
    message TEXT NOT NULL,
    severity VARCHAR(20) NOT NULL CHECK (severity IN ('Low','Medium','High','Critical')),
    is_resolved BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Ground_Station (
    station_id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    location TEXT,
    status VARCHAR(30) DEFAULT 'Active'
);

CREATE TABLE Communication_Window (
    window_id SERIAL PRIMARY KEY,
    station_id INT NOT NULL REFERENCES Ground_Station(station_id) ON DELETE CASCADE,
    spacecraft_id INT NOT NULL REFERENCES Spacecraft(spacecraft_id) ON DELETE CASCADE,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP NOT NULL,
    CHECK (end_time > start_time)
);

CREATE TABLE Experiment (
    experiment_id SERIAL PRIMARY KEY,
    mission_id INT NOT NULL REFERENCES Mission(mission_id) ON DELETE CASCADE,
    name VARCHAR(100) NOT NULL,
    status VARCHAR(30) DEFAULT 'Planned',
    lead_scientist_id INT REFERENCES Users(user_id),
    result_data BYTEA
);

CREATE TABLE Mission_Crew (
    assignment_id SERIAL PRIMARY KEY,
    mission_id INT NOT NULL REFERENCES Mission(mission_id) ON DELETE CASCADE,
    astronaut_id INT NOT NULL REFERENCES Users(user_id) ON DELETE CASCADE,
    role VARCHAR(50),
    assigned_at DATE DEFAULT CURRENT_DATE,
    UNIQUE(mission_id, astronaut_id) -- Prevent duplicate assignments to same mission
);

-- 5. Audit Logging
CREATE TABLE AuditLog (
    log_id SERIAL PRIMARY KEY,
    action VARCHAR(50) NOT NULL, -- e.g., 'INSERT', 'UPDATE', 'DELETE'
    table_name VARCHAR(50) NOT NULL,
    record_id INT, -- Generic reference to the primary key of the affected row
    old_data JSONB, -- Requires PostgreSQL
    new_data JSONB,
    changed_by INT REFERENCES Users(user_id), -- If we can track the user
    changed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    details TEXT
);

COMMIT;
